### ISSUE TITLE
libcublas.so ImportError on a Linux gpu environment

### ISSUE THREAD

**Issue by riwim** [ctlearn-project/ctlearn#122]
Hi all, I'm currently working on my master thesis on gamma/hadron separation with multiple images from CTA.

Following the install instructions for a gpu environment on a Linux system I had some problems to get a working system.

`python run_model.py my_config.yml --mode train`

fails with an import error:

`ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory`.

Being inspired by https://github.com/tensorflow/tensorflow/issues/26182#issuecomment-468882301 I changed
```yaml
# conda env create -f environment-gpu.yml
name: ctlearn
channels:
    - anaconda
dependencies:
    - python=3.7.3
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - pip:
        # TensorFlow-GPU v1.13.1
        - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.13.1-cp37-cp37m-linux_x86_64.whl
```
in `environment-gpu.yml` to
```yaml
# conda env create -f environment-gpu.yml
name: ctlearn
channels:
    - anaconda
dependencies:
    - python=3.7.3
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - tensorflow
    - cudatoolkit
    - cudnn
    # - pip:
        # TensorFlow-GPU v1.13.1
        # - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.13.1-cp37-cp37m-linux_x86_64.whl
```
With these changes I can now execute `run_model.py`.
