### ISSUE TITLE
Deep copy nested dicts in run_multiple_configurations.py run combinations file

### ISSUE THREAD

**Issue by aribrill** [ctlearn-project/ctlearn#47]
Dictionary config arguments in the run combinations file outputted by run_multiple_configurations.py are sometimes not deep copied, with references appearing instead of the actual configuration parameter. For example, this occurs in the layers parameter recorded in run_combinations.py created when running the v0.2.0 benchmark config (snippet below). This issue doesn't seem to affect performance, just the appearance of the parameters in the saved file.

```
run00:
  batch_size: 64
  example_type: single_tel
  layers: &id001
  - filters: 32
    kernel_size: 3
  - filters: 32
    kernel_size: 3
  - filters: 64
    kernel_size: 3
  - filters: 128
    kernel_size: 3
  learning_rate: 5.0e-05
  model:
    function: single_tel_model
    module: single_tel
  sorting: null
  tel_type: LST
run01:
  batch_size: 16
  example_type: array
  layers: *id001
  learning_rate: 0.0001
  model:
    function: cnn_rnn_model
    module: cnn_rnn
  sorting: size
  tel_type: LST
```
